name: kinfox_biller
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  get: ^4.7.3
  http: ^1.6.0
  fluttertoast: ^9.0.0
  flutter_screenutil: ^5.9.3
  mobile_scanner: ^7.2.0
  data_table_2: ^2.7.2
  intl: ^0.20.2
  flutter_thermal_printer: ^2.0.1


  cupertino_icons: ^1.0.8
  image: ^4.8.0
  path_provider: ^2.1.5
  flutter_libserialport: ^0.6.0
  flutter_barcode_listener: ^0.1.4
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/


  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Variable.ttf
        - asset: assets/font/Inter-Italic.ttf
          style: italic
